spring.application.name=notesPatients
spring.mongodb.host=${HOST_MONGO_BDD}
spring.mongodb.port=${PORT_MONGO_BDD}
spring.mongodb.database=${DATABASE_MONGO_BDD}

server.port=${SERVER_PORT:8080}

# swagger-ui
springdoc.swagger-ui.path=/doc
springdoc.api-docs.path=/patient/note/v3/api-docs
api.server.gateway.url=${API_SERVER_GATEWAY_URL}